version: '2'
services:
  app:
    container_name: docker-mongo-react-microservice
    restart: always
    build: .
    ports:
      - '5000:3000'
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'